title: Math 8xyz - Mathematical epidemiology
logo: /SLIDES/FIGS-slides-admin/Gemini_Generated_Image_5yvymh5yvymh5yvy.jpeg
description: This is course material for a graduate course on mathematical epidemiology
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
