title: Math 8xyz - Mathematical Epidemiology
logo: /assets/img/Gemini-generated-viruses-bacteria-2.jpeg
description: This is course material for a graduate course on mathematical epidemiology
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
