\documentclass[aspectratio=169]{beamer}

% Set lecture number for later use
<<set-lecture-number,echo=FALSE>>=
lecture_number = "16"
@

% Part common to all the lectures
\subtitle{MATH 8xyz -- Lecture \Sexpr{lecture_number}}
\author{\texorpdfstring{Julien Arino\newline Department of Mathematics @ University of Manitoba \newline Maud Menten Institute @ PIMS\newline\url{julien.arino@umanitoba.ca}}{Julien Arino}}
\date{Winter 20XX}

% Title of the lecture
\title{Group models}

<<set-options,echo=FALSE,warning=FALSE,message=FALSE>>=
# Source the code common to all lectures
source("common-code.R")
@

<<set-slide-background,echo=FALSE,results='asis'>>=
# Are we plotting for a dark background? Setting is in common-code.R, but
# cat command must run here.
cat(input_setup)
@

\begin{document}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% TITLE AND OUTLINE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\titlepagewithfigure{FIGS-slides-admin/Gemini_Generated_Image_4oxcef4oxcef4oxc.jpeg}
\outlinepage{FIGS-slides-admin/Gemini_Generated_Image_tzvf9ztzvf9ztzvf.jpeg}

%%%%%%%%%%%%%%%%%%%%
\section{Formulating group models}
\begin{frame}{Formulating group models}
\bbullet Age-structured models
\bbullet Models incorporating social structure
\bbullet Models with pathogen heterogeneity
\bbullet Models with immunological component
\end{frame}

\begin{frame}{Limitations of single population ODE models}
\bbullet Basic ODEs assume all individuals in a compartment are roughly the same
\bbullet Individuals can spend differing times in a compartment, but they are all the same
\bbullet As seen with COVID-19, different age groups are impacted differently
\end{frame}

\begin{frame}{Groups can be used for many things}
\bbullet Groups allow to introduce structure in a population without using PDEs
\begin{itemize}
  \item Age structure
  \item Social structure
  \item Pathogen heterogeneity
  \item Host heterogeneity (e.g., super spreaders)
\end{itemize}
\vfill
\bbullet In this lecture, we do not consider spatial heterogeneity; this is done in Lecture 05
\bbullet We start by considering a few examples
\end{frame}

\section{Age-structured models}
\begin{frame}{Age-structured models}
\bbullet ODEs are not the best way to incorporate structure such as age
\bbullet Will come back to this in Lecture 09, but give one example here
\end{frame}

\begin{frame}{A multi-group SIS model with age structure}
\bbullet Feng, Huang \& C$^3$ (2004)
\bbullet For $i=1,\ldots,n$ different subgroups:
\[
\left(
\frac{\partial}{\partial t}+\frac{\partial}{\partial a}
\right)S_i = -\mu_i(a)S_i(t,a)-\Lambda_i(a,I(t,\cdot))S_i(t,a)+\gamma_i(a)I_i(t,a)
\]
\[
\left(
\frac{\partial}{\partial t}+\frac{\partial}{\partial a}
\right)I_i = -\mu_i(a)I_i(t,a)+\Lambda_i(a,I(t,\cdot))S_i(t,a)-\gamma_i(a)I_i(t,a)
\]
where
\[
\Lambda_i(a,I(\cdot,t)):=K_i(a)I_i(a,t)+\sum_{j=1}^n \int_0^\omega K_{ij}(a,s)I_j(s,t)\ ds
\]
\end{frame}

\begin{frame}{Boundary and initial conditions}
For $i=1,\ldots,n$:
\[
S_i(t,0) = \int_0^\omega b_i(a)[S_i(t,a)+(1-q_i)I_i(t,a)]\ da
\]
\[
I_i(t,0) = q_i\int_0^\omega b_i(a)I_i(t,a)\ da,\quad 0<q_1<1
\]
\[
S_i(0,a) = \psi(a)
\]
\[
I_i(0,a) = \varphi(a)
\]
($q_i$ fraction of newborns that is infected)
\vfill
Basic reproduction number in group $i=1,\ldots,n$:
\[
\mathcal{R}_i = \int_0^\omega b_i(a)\exp\left(-\int_0^a \mu_i(\tau)d\tau\right)\ da
\]
\end{frame}

\begin{frame}{Remarks}
\bbullet Authors obtain some results in terms of global stability
\bbullet Need simplifications to move forward
\bbullet No numerics, because numerics for such models are hard
\end{frame}

\begin{frame}{Going the ODE route}
\bbullet ODEs are way less satisfactory but can be used as-is and are much easier numerically
\bbullet Caveat: ODE models with age structure are intrinsically wrong, since sojourn times in an age group is exponentially distributed instead of Dirac distributed!
\end{frame}

\section{Models incorporating social structure}
\begin{frame}{Models incorporating social structure}
\bbullet Example: TB in foreign-born population of Canada
\bbullet Varughese, Langlois-Klassen, Long, \& Li (2014)
\bbullet New immigrants to Canada come predominantly from countries in which TB is very active
\bbullet People develop TB in the first few years of their presence in Canada
\bbullet Want to investigate this, together with effect of various screening measures
\end{frame}

\maxFrameImage{FIGS/VarugheseLangloisklassenLongLi-2014-TB-flow_diagram.png}

\section{Models with pathogen heterogeneity}
\begin{frame}{Models with pathogen heterogeneity}
\bbullet Example: Importation of a new SARS-CoV-2 variant
\bbullet Arino, Bo\"elle, Milliken \& Portet (2021)
\bbullet Consider what happens when a new variant N arrives in a situation where another variant O is already circulating
\end{frame}

\maxFrameImage{FIGS/importation_model_2variants.jpg}

\begin{frame}{Coupling is through the force of infection}
\bbullet For now, we have discussed incidence functions $f(S,I,N)$
\bbullet Here, we use a force of infection $\Phi_X$, for $X\in\{O,N\}$
\bbullet Force of infection uses $S$ outside of function: it is the pressure that applies to $S$ individuals to make them infected
\bbullet Of course, the two are equivalent, but in some contexts, it makes sense to use this
\bbullet Here, for $X\in\{O,N\}$:
\[
\Phi_X = \beta_X(\eta_{X}L_{X_C2}+\xi_X(D_{X_C1}+D_{X_C2})+U_{X_C1}+U_{X_C2})
\]
\end{frame}

\begin{frame}{Adding more groups - Importation layer}
\bbullet How can we evaluate how much importations contribute to propagation within a location?
\bbullet If an individual arrives in a new location while bearing the disease, we put them in a special group, the importation layer
\bbullet In importation layer, individuals make contacts with others in the population, but they remain in the importation layer until recovery or death
\end{frame}

\maxFrameImage{FIGS/importation_model_2variants_import_layer.jpg}

\begin{frame}{Force of infection with importation layer}
For $X\in\{O,N\}$:
\[
\Phi_X = \Phi_{X_I}+\Phi_{X_I}
\]
where, for $X\in\{O,N\}$ and $Z\in\{I,C\}$:
\[
\Phi_{X_Z} = \beta_X(\eta_{X}L_{X_Z2}+\xi_X(D_{X_Z1}+D_{X_Z2})+U_{X_Z1}+U_{X_Z2})
\]
\end{frame}

\section{Models with immunological component}
\begin{frame}{Models with immunological component}
\bbullet Global dynamics of a general class of multistage models for infectious diseases. Guo, Li \& Shuai (2012)
\bbullet Viruses such as HIV reside in the body for a very long time, potentially for life
\bbullet Throughout the course of this residence, virus loads change and with it symptoms and infectiousness
\end{frame}

\maxFrameImage{FIGS/GuoLiShuai-2012-multistage-flow_diagram.png}

\section{Analysing group models}
\begin{frame}{Analysing group models}
\bbullet For general considerations about a method, see Lu \& Shuai (2010)
\bbullet Techniques use combination of classical ODE stability theory, linear algebra and graph theory
\bbullet They show GAS when $\mathcal{R}_0\leq 1$ and GAS under conditions when $\mathcal{R}_0>1$
\bbullet Use Lyapunov function $L=\sum_{i=1}^nw_iI_i$ for DFE when $\mathcal{R}_0\leq 1$
\bbullet For EEP, use a Goh type Lyapunov function:
\[
V=\tau_1\int_{S^*}^{S}\frac{\Phi(\xi)-\Phi(S^*)}{\Phi(\xi)}d\xi+\sum_{i=1}^n\tau_i\int_{I_i^*}^{I_i}\frac{\psi(\xi)-\psi(I_i^*)}{\psi(\xi)}d\xi
\]
\bbullet Use Kirchhoff’s matrix tree theorem to show that $V'$ is negative definite
\end{frame}

\section{Simulating group models}
\begin{frame}{Simulating group models}
\bbullet This is very similar to metapopulation models which are described in Practicum 02
\bbullet The variant importation model simulations will be discussed in the stochastic lectures
\end{frame}

%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
% Convert the file to R code. Only include if including R code in the document,
% otherwise it will generate a meaningless file with just R and knitr options.
% <<convert-Rnw-to-R,warning=FALSE,message=FALSE,echo=FALSE,results='hide'>>=
% rmd_chunks_to_r_temp()
% @

%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%
\begin{frame}[allowframebreaks]{Bibliography}
\bibliographystyle{apalike}
\bibliography{local-bibliography}
\end{frame}


\end{document}
